"""Filesystem port. Protocol only — read/write/exec existence checks."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol


class FileSystem(Protocol):
    def exists(self, path: Path) -> bool: ...

    def is_dir(self, path: Path) -> bool: ...

    def is_file(self, path: Path) -> bool: ...

    def is_symlink(self, path: Path) -> bool: ...

    def read_text(self, path: Path) -> str: ...

    def write_text(self, path: Path, text: str) -> None: ...

    def ensure_dir(self, path: Path) -> None: ...

    def rename(self, src: Path, dst: Path) -> None: ...

    def which(self, name: str) -> str | None: ...
