"""Git operations port. Protocol only, no implementation."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol


class GitPort(Protocol):
    def available(self) -> bool: ...

    def is_repo(self, path: Path) -> bool: ...

    def is_ziro_repo(self, path: Path) -> bool: ...

    def origin_kind(self, path: Path) -> str | None: ...

    def heal_origin(self, path: Path) -> bool: ...

    def clone(self, url: str, dest: Path, depth: int | None = None) -> None: ...

    def pull_ff_only(self, path: Path) -> bool: ...

    def has_uncommitted_changes(self, path: Path) -> bool: ...

    def stash(self, path: Path) -> bool: ...

    def stash_pop(self, path: Path) -> bool: ...

    def migrate_legacy(self, home: Path, dry_run: bool = False) -> tuple[Path, bool]: ...
