"""Console UI port. Protocol only, no implementation."""

from __future__ import annotations

from typing import Protocol


class ConsoleUI(Protocol):
    def info(self, msg: str) -> None: ...

    def success(self, msg: str) -> None: ...

    def warn(self, msg: str) -> None: ...

    def error(self, msg: str) -> None: ...

    def installed(self, msg: str) -> None: ...

    def present(self, msg: str) -> None: ...

    def configured(self, msg: str) -> None: ...

    def updated(self, msg: str) -> None: ...

    def skipped(self, msg: str) -> None: ...

    def failed(self, msg: str) -> None: ...

    def section(self, title: str) -> None: ...

    def banner(self) -> None: ...

    def prompt(self, msg: str) -> None: ...

    def confirm(self, question: str, default_yes: bool = True) -> bool: ...

    def getting_started(self, lines: list[str]) -> None: ...
