"""Parity tests — deferred vs eager behavior.

Spec 002 R6: verify deferred plugins produce equivalent
user-visible output to eager loading.
"""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path.home() / ".ziro"))

from core.generator import generate, EmitOptions
from core.models import Strategy
from core.resolver import ResolvedConfig


class TestParityStructure(unittest.TestCase):
 def test_both_strategies_emit_znap_source(self):
  """Both eager and deferred ultimately call `znap source`."""
  with tempfile.TemporaryDirectory() as tmp:
   out = Path(tmp) / "plugins.gen.zsh"
   configs = [
    ResolvedConfig("plugin-a", Strategy.EAGER),
    ResolvedConfig("plugin-b", Strategy.AFTER_PROMPT, defer_slot="b"),
   ]
   generate(configs, out, options=EmitOptions(enforce_order=False))
   content = out.read_text()
   self.assertIn("znap source plugin-a", content)
   self.assertIn("znap source plugin-b", content)

 def test_defer_wraps_but_keeps_source(self):
  """Deferred line contains both ziro-defer and znap source."""
  with tempfile.TemporaryDirectory() as tmp:
   out = Path(tmp) / "plugins.gen.zsh"
   configs = [
    ResolvedConfig("p", Strategy.AFTER_PROMPT, defer_slot="b"),
   ]
   generate(configs, out)
   content = out.read_text()
   self.assertIn("ziro-defer", content)
   self.assertIn("znap source p", content)

 def test_eval_cache_parity_with_eager(self):
  """Eval-cached plugins still emit valid zsh."""
  with tempfile.TemporaryDirectory() as tmp:
   out = Path(tmp) / "plugins.gen.zsh"
   configs = [
    ResolvedConfig("starship", Strategy.EAGER, eval_cache=True),
   ]
   generate(configs, out)
   content = out.read_text()
   self.assertIn("znap eval", content)

 def test_header_present_for_all_strategies(self):
  with tempfile.TemporaryDirectory() as tmp:
   out = Path(tmp) / "plugins.gen.zsh"
   configs = [
    ResolvedConfig("a", Strategy.EAGER),
    ResolvedConfig("b", Strategy.AFTER_PROMPT),
    ResolvedConfig("c", Strategy.LAZY),
   ]
   generate(configs, out)
   self.assertTrue(out.read_text().startswith("# AUTO-GENERATED by ziro"))


if __name__ == "__main__":
 unittest.main()