"""Tests for core.doctor."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path.home() / ".ziro"))

from core.doctor import verify_generated


class TestDoctor(unittest.TestCase):
    def test_missing_artifact_unhealthy(self):
        with tempfile.TemporaryDirectory() as tmp:
            r = verify_generated(Path(tmp))
            self.assertFalse(r.healthy)
            self.assertTrue(any("missing" in i for i in r.issues))

    def test_healthy_artifact(self):
        with tempfile.TemporaryDirectory() as tmp:
            cfg = Path(tmp)
            derived = cfg / "derived"
            derived.mkdir(parents=True)
            (derived / "plugins.gen.zsh").write_text(
                "# AUTO-GENERATED by ziro — do not edit\nznap source x\n"
            )
            r = verify_generated(cfg)
            self.assertTrue(r.healthy)

    def test_hand_edited_unhealthy(self):
        with tempfile.TemporaryDirectory() as tmp:
            cfg = Path(tmp)
            derived = cfg / "derived"
            derived.mkdir(parents=True)
            (derived / "plugins.gen.zsh").write_text("# hand edited\n")
            r = verify_generated(cfg)
            self.assertFalse(r.healthy)
            self.assertTrue(any("header" in i.lower() for i in r.issues))


if __name__ == "__main__":
    unittest.main()
