"""ziro-shell — plugins.gen.zsh generator (Schema C).

Layer: 3 (Python core, cold-path only)
Spec: 003
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from core.models import Strategy
from core.resolver import ResolvedConfig


HEADER_LINE = "# AUTO-GENERATED by ziro — do not edit"
SCHEMA_VERSION = "0.1.0"


def _emit(cfg: ResolvedConfig) -> str:
    """Emit one zsh line for resolved config."""
    plugin = cfg.plugin

    # Raw escape hatch
    if cfg.raw:
        return cfg.raw

    if cfg.strategy == Strategy.EAGER:
        if cfg.eval_cache:
            return f"znap eval {plugin} '{plugin} init'"
        return f"znap source {plugin}"

    if cfg.strategy in (Strategy.AFTER_PROMPT, Strategy.LAZY):
        slot = f" --slot={cfg.defer_slot}" if cfg.defer_slot else ""
        return f"ziro-defer{slot} znap source {plugin}"

    return f"znap source {plugin} # unknown strategy → eager fallback"


def generate(
    configs: list[ResolvedConfig],
    output_path: Path,
    *,
    generated_at: str | None = None,
) -> Path:
    """Write plugins.gen.zsh (Schema C). Deterministic for same input."""
    ts = generated_at or datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        HEADER_LINE,
        f"# Schema: {SCHEMA_VERSION}",
        f"# Generated: {ts}",
        "",
    ]

    for cfg in configs:
        lines.append(_emit(cfg))

    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    return output_path


def default_output_path(config_dir: Path) -> Path:
    return config_dir / "derived" / "plugins.gen.zsh"


__all__ = ["generate", "default_output_path", "HEADER_LINE", "SCHEMA_VERSION"]
