"""ziro-shell — plugins.gen.zsh generator (Schema C).

Layer: 3 (znap Runtime)
Spec: 002 (load order) + Spec 003 (Schema C)
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from core.ziro_load import LoadSpec, emit, from_resolved


HEADER_LINE = "# AUTO-GENERATED by ziro — do not edit"
SCHEMA_VERSION = "0.1.0"


# Fixed load order per Spec 002 R3
LOAD_ORDER = [
    "zsh-completions",   # 1. Eager, before compinit
    "ohmyzsh-git",       # 2. Eager, compdef
    "# compinit",        # 3. Marker
    "starship",          # 4. Eval-cache
    "fzf",               # 5. Eval-cache
    "ziro-ghost",        # 6. Ziro-defer
    "fast-syntax-highlighting",  # 7. Ziro-defer
    "zcolors",           # 8. Eval-cache
    "zoxide",            # 9. Eval-cache
    "ohmyzsh-colored-man-pages",  # 10. Ziro-defer
]


@dataclass(frozen=True)
class EmitOptions:
    """Options for generator."""
    enforce_order: bool = True
    generated_at: str = ""


def _emit_plugin(
    plugin: str,
    strategy: str,
    *,
    compile_: bool = True,
    eval_cache: bool = False,
    pick: str = "",
    wait: str = "",
    defer_slot: str = "",
    raw: str = "",
) -> str:
    """Emit zsh line for one plugin via ziro_load."""
    spec = from_resolved(
        plugin=plugin,
        strategy=strategy,
        compile_=compile_,
        eval_cache=eval_cache,
        pick=pick,
        wait=wait,
        defer_slot=defer_slot,
        raw=raw,
    )
    return emit(spec)


def generate(
    configs: list,  # list[ResolvedConfig]
    output_path: Path,
    *,
    options: EmitOptions | None = None,
) -> Path:
    """Write plugins.gen.zsh (Schema C). Deterministic for same input."""
    opts = options or EmitOptions()
    ts = opts.generated_at or datetime.now(timezone.utc).isoformat()

    # Sort configs by load order if requested
    ordered = list(configs)
    if opts.enforce_order:
        def order_key(cfg):
            try:
                return LOAD_ORDER.index(cfg.plugin)
            except ValueError:
                return len(LOAD_ORDER)  # unknown → end
        ordered = sorted(configs, key=order_key)

    lines: list[str] = [
        HEADER_LINE,
        f"# Schema: {SCHEMA_VERSION}",
        f"# Generated: {ts}",
        "",
    ]

    for cfg in ordered:
        line = _emit_plugin(
            plugin=cfg.plugin,
            strategy=cfg.strategy.value if hasattr(cfg.strategy, "value") else str(cfg.strategy),
            compile_=getattr(cfg, "compile", True),
            eval_cache=getattr(cfg, "eval_cache", False),
            pick=getattr(cfg, "pick", ""),
            wait=getattr(cfg, "wait", ""),
            defer_slot=getattr(cfg, "defer_slot", ""),
            raw=getattr(cfg, "raw", ""),
        )
        lines.append(line)

    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    return output_path


def default_output_path(config_dir: Path) -> Path:
    return config_dir / "derived" / "plugins.gen.zsh"


__all__ = [
    "generate",
    "default_output_path",
    "HEADER_LINE",
    "SCHEMA_VERSION",
    "LOAD_ORDER",
    "EmitOptions",
]
