"""ziro-shell — install command.

Layer: 3 (Python core, cold-path only)
Spec: 006 R1
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def _config_dir() -> Path:
    base = os.environ.get("ZIRO_CONFIG")
    if base:
        return Path(base)
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "ziro"


def _write_defaults(cfg: Path) -> None:
    """Write minimal defaults.toml (hand-rolled)."""
    cfg.mkdir(parents=True, exist_ok=True)
    defaults = cfg / "defaults.toml"
    if defaults.is_file():
        return
    content = "# ziro-shell — user defaults\n"
    content += "# Editable by hand. Regenerated only on `ziro config reset`.\n"
    content += "\n"
    content += "[version]\n"
    content += 'schema = "0.1.5"\n'
    content += "\n"
    content += "[prompt]\n"
    content += 'default = "starship"\n'
    defaults.write_text(content)


def _write_tools(cfg: Path) -> None:
    """Write minimal tools.toml (empty registry)."""
    cfg.mkdir(parents=True, exist_ok=True)
    tools = cfg / "tools.toml"
    if tools.is_file():
        return
    content = "# AUTO-GENERATED by ziro — do not edit manually\n"
    content += "# Registry of known tools.\n"
    content += "\n"
    content += "[meta]\n"
    content += 'schema = "0.1.5"\n'
    content += 'count = 0\n'
    tools.write_text(content)


def cmd_install(argv: list[str]) -> int:
    dry_run = "--dry-run" in argv
    default_mode = "--default" in argv
    custom_mode = "--custom" in argv

    cfg = _config_dir()

    print("ziro-shell installer")
    print("─" * 40)

    if default_mode:
        choice = "default"
    elif custom_mode:
        choice = "custom"
    else:
        # Interactive question (only if TTY)
        if sys.stdin.isatty():
            print("How would you like to proceed?")
            print(" [1] Default — install with pre-configured defaults")
            print(" [2] Custom — choose each component manually")
            try:
                ans = input("Choice [1]: ").strip() or "1"
            except EOFError:
                ans = "1"
            choice = "custom" if ans == "2" else "default"
        else:
            choice = "default"  # non-TTY → default

    print(f"mode: {choice}")

    if dry_run:
        print("[dry-run] would write defaults.toml, tools.toml")
        return 0

    _write_defaults(cfg)
    _write_tools(cfg)
    print(f"✅ wrote: {cfg}/defaults.toml")
    print(f"✅ wrote: {cfg}/tools.toml")
    print("")
    print("Next: ziro plugin add <name>")
    return 0


def main(argv: list[str]) -> int:
    return cmd_install(argv)


__all__ = ["main"]
