"""Built-in Starship prompt themes.

A theme is a raw starship.toml template with two @-placeholders:
  @SEGMENTS@  -> language modules derived from ENABLE_* flags (apply time;
                 re-run `ziro theme apply` after changing language flags)
  @NAME@      -> theme name (for the generated-by header marker)

Re-applying a theme overwrites the file only when it carries our marker,
so user-customized configs are never touched.
"""

SEGMENT_MODULES = {
    "ENABLE_PYTHON": "$python",
    "ENABLE_RUST": "$rust",
    "ENABLE_GO": "$golang",
    "ENABLE_NODE": "$nodejs",
}

# Language module blocks shared by all themes; appended after the template.
LANG_MODULE_TOML = """\
[python]
format = "([$symbol$version (venv: $virtualenv)]($style) )"
style = "bold yellow"

[rust]
format = "([$symbol$version]($style) )"
style = "bold red"

[golang]
format = "([$symbol$version]($style) )"
style = "bold cyan"

[nodejs]
format = "([$symbol$version]($style) )"
style = "bold green"
"""

THEMES: dict[str, dict[str, str]] = {
    "lambda": {
        "description": "Ziro default: user@host, dir, git, lambda character",
        "template": r'''
# Generated by ziro theme '@NAME@' (@MARKER@)
# ~/.config/starship.toml

add_newline = true
command_timeout = 2000

format = """@SEGMENTS@${custom.userinfo}$directory$git_status($git_branch) $cmd_duration
$character
"""

@LANG_TOML@
[custom.userinfo]
command = "printf '%s@%s ➜ ' \\"$USER\\" \\"$(uname -n)\\""
when = "true"
style = "bold 242"

[directory]
truncate_to_repo = true
format = "[$path ](bold blue)"
style = "bold blue"

[git_branch]
symbol = "  "
format = "[$symbol$branch](bold yellow)"
truncation_length = 8
style = "bold yellow"

[git_status]
format = "[$all_status$ahead_behind](bold purple)"
style = "bold purple"
conflicted = "⚔️($count)"
ahead = "↑($count)"
behind = "↓($count)"
diverged = "↕($count)"
untracked = "★($count)"
stashed = "📍($count)"
modified = " ✏️($count)"
staged = "✔($count)"
renamed = "➜($count)"
deleted = "🗑($count)"

[cmd_duration]
min_time = 2000
format = "[ ⏱ took $duration](bold green)"
style = "bold green"

[character]
success_symbol = "[ λ](bold green)"
error_symbol = "[ λ](bold red)"
vicmd_symbol = "[ λ](bold yellow)"
format = "$symbol "
''',
    },
    "minimal": {
        "description": "Single line, no userinfo, quiet git status",
        "template": r'''
# Generated by ziro theme '@NAME@' (@MARKER@)
# ~/.config/starship.toml

add_newline = false
command_timeout = 2000

format = """@SEGMENTS@$directory$git_branch$git_status $cmd_duration$character"""

@LANG_TOML@
[directory]
truncate_to_repo = true
style = "bold blue"

[git_branch]
format = "on [$branch](bold yellow) "
truncation_length = 8

[git_status]
format = "[[$all_status$ahead_behind]](bold purple) "

[cmd_duration]
min_time = 3000
format = "[$duration] "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold yellow)"
''',
    },
    "plain": {
        "description": "Server-friendly: ASCII only, no emoji, minimal noise",
        "template": r'''
# Generated by ziro theme '@NAME@' (@MARKER@)
# ~/.config/starship.toml

add_newline = false
command_timeout = 2000

format = """@SEGMENTS@$directory$git_branch$git_status $cmd_duration
$character"""

@LANG_TOML@
[directory]
truncate_to_repo = true
style = "bold blue"

[git_branch]
format = "[$branch](bold yellow) "
truncation_length = 8

[git_status]
format = "[$all_status$ahead_behind](bold red) "

[cmd_duration]
min_time = 5000
format = "[$duration](bold green) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[>](bold yellow)"
format = "$symbol "
''',
    },
    "twoline": {
        "description": "Two lines, nerd-font icons, colorful git",
        "template": r'''
# Generated by ziro theme '@NAME@' (@MARKER@)
# ~/.config/starship.toml

add_newline = true
command_timeout = 2000

format = """@SEGMENTS@$directory$git_branch$git_status
$character"""

@LANG_TOML@
[directory]
truncate_to_repo = true
format = "[ $path ](bold blue)"
style = "bold blue"

[git_branch]
symbol = " "
format = "[$symbol$branch](bold purple) "
truncation_length = 8

[git_status]
format = "[$all_status$ahead_behind](bold red) "

[cmd_duration]
min_time = 2000
format = "[ $duration](bold yellow)"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
vicmd_symbol = "[➜](bold yellow) "
''',
    },
}

DEFAULT_THEME = "lambda"
_HEADER = "# Generated by ziro theme"


def language_segments(enabled: dict[str, bool]) -> str:
    """Render the language module segment string from ENABLE_* flags."""
    return "".join(
        module for key, module in SEGMENT_MODULES.items() if enabled.get(key)
    )


def enabled_from_env(get_flag) -> dict[str, bool]:
    """Build the enabled map using a callable returning the flag value."""
    return {key: bool(get_flag(key)) for key in SEGMENT_MODULES}


def marker(enabled: dict[str, bool]) -> str:
    return " ".join(
        f"{key.removeprefix('ENABLE_').lower()}={'on' if enabled.get(key) else 'off'}"
        for key in SEGMENT_MODULES
    )


def render(name: str, enabled: dict[str, bool]) -> str:
    theme = THEMES[name]
    body = theme["template"].replace("@LANG_TOML@", LANG_MODULE_TOML)
    return (body
            .replace("@SEGMENTS@", language_segments(enabled))
            .replace("@NAME@", name)
            .replace("@MARKER@", marker(enabled)))


def is_managed(path) -> bool:
    """True if the file was generated by us (safe to overwrite)."""
    try:
        return _HEADER in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
