"""`ziro theme` command: list / current / apply."""

import os
import shutil
from pathlib import Path

from . import theme, ui

CONFIG_PATH = Path.home() / ".config" / "starship.toml"


def _enabled_flags(overrides: dict[str, bool] | None = None) -> dict[str, bool]:
    """Read ENABLE_* from the environment (set by .zshrc.local).

    `overrides` wins per-key (installer passes its resolved language flags).
    """
    flags = theme.enabled_from_env(lambda key: os.environ.get(key, "yes") != "no")
    if overrides:
        for key, val in overrides.items():
            if key in flags:
                flags[key] = val
    return flags


def _current_theme() -> str | None:
    """Theme name from the managed-file marker, or None if unmanaged/absent."""
    try:
        for line in CONFIG_PATH.read_text(encoding="utf-8", errors="replace").splitlines()[:3]:
            if line.startswith(theme._HEADER):  # noqa: SLF001
                for name in theme.THEMES:
                    if f"'{name}'" in line:
                        return name
                return None
    except OSError:
        pass
    return None


def run(command: str | None, name: str | None) -> int:
    if command in (None, "list"):
        return _list()
    if command == "current":
        return _current()
    if command == "apply":
        return _apply(name)
    ui.error(f"unknown theme command: {command}")
    return 2


def _list() -> int:
    current = _current_theme()
    for name, t in sorted(theme.THEMES.items()):
        mark = ui.GREEN + " (current)" + ui.RESET if name == current else ""
        print(f"{ui.BOLD}{name}{ui.RESET}{mark} - {t['description']}")
    if current is None and CONFIG_PATH.exists() and not theme.is_managed(CONFIG_PATH):
        ui.info(f"~/.config/starship.toml is user-owned; themes will not overwrite it")
    else:
        ui.info("apply with: ziro theme apply <name>")
    return 0


def _current() -> int:
    current = _current_theme()
    if current:
        print(current)
        return 0
    if CONFIG_PATH.exists():
        ui.info("custom starship.toml (not managed by ziro)")
    else:
        ui.info("no theme applied yet")
    return 1


def _apply(name: str | None) -> int:
    if not name:
        return _apply_interactive()
    if name not in theme.THEMES:
        ui.error(f"unknown theme '{name}'. Available: {', '.join(sorted(theme.THEMES))}")
        return 2
    return _write(name)


def _apply_interactive(lang_flags: dict[str, bool] | None = None) -> int:
    names = sorted(theme.THEMES)
    print()
    for i, n in enumerate(names, 1):
        print(f"  {i}) {n:10s} {theme.THEMES[n]['description']}")
    print()
    ui.prompt("Theme number or name [1]: ")
    answer = input().strip().lower()
    if not answer:
        answer = "1"
    if answer.isdigit() and 1 <= int(answer) <= len(names):
        chosen = names[int(answer) - 1]
    elif answer in theme.THEMES:
        chosen = answer
    else:
        ui.error(f"unknown theme '{answer}'")
        return 2
    return _write(chosen, lang_flags)


def _write(name: str, enabled: dict[str, bool] | None = None) -> int:
    if CONFIG_PATH.exists() and not theme.is_managed(CONFIG_PATH):
        ui.error(f"{CONFIG_PATH} is user-owned (not generated by ziro); not overwriting.")
        ui.info("Remove it or hand-edit it, then re-run: ziro theme apply " + name)
        return 1
    enabled = enabled if enabled is not None else _enabled_flags()
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(theme.render(name, enabled), encoding="utf-8")
    ui.configured(f"~/.config/starship.toml -> theme '{name}'")
    if not shutil.which("starship"):
        ui.warn("starship not installed; prompt will activate after install")
    else:
        ui.info("restart your terminal or run: source ~/.zshrc")
    return 0
